name: astroquery

channels:
    - astropy

dependencies:
    - python=>3
    - pip
    - astropy
    - Cython
    - matplotlib
    - numpy
    - requests
    - scipy
    - pip:
      - sphinx-astropy
