language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

python:
    - 2.7
    - 3.4
    - 3.5

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - MAIN_CMD='python setup.py'
        - NUMPY_VERSION=1.10
        - ASTROPY_VERSION=stable
        - CONDA_DEPENDENCIES='requests beautifulsoup4 matplotlib html5lib keyring aplpy pyregion'
        - SETUP_CMD='test'

    matrix:
        - SETUP_CMD='egg_info'

        - SETUP_CMD='test'

matrix:
    include:
        # Do a coverage test in Python 2.
        - python: 2.7
          env: SETUP_CMD='test --coverage'

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - python: 2.7
          env: SETUP_CMD='build_sphinx -w'

        # Python 3.3 doesn't have numpy 1.10 in conda, revoke this commit once
        # it's available in the astropy-ci-extras channel
        - python: 3.3
          env: SETUP_CMD='egg_info'
        - python: 3.3
          env: NUMPY_VERSION=1.9

        # Try Astropy development and LTS version
        - python: 2.7
          env: ASTROPY_VERSION=development
        - python: 3.5
          env: ASTROPY_VERSION=development
        - python: 2.7
          env: ASTROPY_VERSION=lts
        - python: 3.5
          env: ASTROPY_VERSION=lts

        # Try with optional dependencies disabled
        - python: 2.7
          env: CONDA_DEPENDENCIES='requests beautifulsoup4 html5lib keyring'
        - python: 3.5
          env: CONDA_DEPENDENCIES='requests beautifulsoup4 html5lib keyring'

        # Try older numpy versions
        - python: 2.7
          env: NUMPY_VERSION=1.9
        - python: 2.7
          env: NUMPY_VERSION=1.8
        - python: 2.7
          env: NUMPY_VERSION=1.7
        - python: 2.7
          env: NUMPY_VERSION=1.6

        # Try numpy pre-release version, this runs only when a pre-release
        # is available on pypi.
        - python: 3.4
          env: NUMPY_VERSION=prerelease

        # Do a PEP8 test with pycodestyle
        - python: 2.7
          env: MAIN_CMD='pycodestyle astroquery --count' SETUP_CMD=''

    allow_failures:
        - env: MAIN_CMD='pycodestyle astroquery --count' SETUP_CMD=''

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
   - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then
          coveralls --rcfile='astroquery/tests/coveragerc';
      fi
